# CI de Nível 01 - Disparo Manual através de clique - Gitlab

# maquina onde o job vai rodar no node.js
        image: node:24
# Stages - etapa da pipeline
        stages: 
        - e2e
# nome do job
        e2e-tests:
# stage que o job vai ser executado         
        stage: e2e
# executado manualmente
        when: manual
# comandos executados        
        script:
# instalação - gerenciador de pacote        
        - npm install -g yarn
# instalando as dependências        
        - yarn
# instalando os navegadores do playwright        
        - yarn playwright install
# executando testes end-to-end com playwright        
        - yarn run e2e